import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { resolveCopies } from "./copy.ts";

/**
 * Fixtures under `tests/fixtures/5etools/` are generated by `pnpm fixtures:build`.
 * They keep the real files' identity fields, `_mod` modes and `_preserve` blocks, and
 * elide the prose, because that text is WotC's and is never committed (see NOTICE).
 * Widen one by naming what it should keep in `packages/content/src/fixtures/declaration.ts`.
 */
const FIXTURES = resolve(import.meta.dirname, "../../../../tests/fixtures/5etools");

type Entry = Record<string, unknown>;

/**
 * One document through a resolver that takes every source a loader read. The
 * cases where a parent sits in another file hand `resolveCopies` the map itself.
 */
function resolveOne(source: unknown, label: string): Entry {
  return resolveCopies(new Map([[label, source]])).get(label) as Entry;
}

function entriesOf(document: Entry, property: string, where: string): Entry[] {
  const entries = document[property];
  if (!Array.isArray(entries)) throw new Error(`${where} has no ${property}`);
  return entries as Entry[];
}

function load(file: string, property: string): Entry[] {
  const parsed = JSON.parse(readFileSync(join(FIXTURES, "data", file), "utf8"));
  return entriesOf(resolveOne(parsed, `data/${file}`), property, file);
}

function find(entries: Entry[], match: Entry): Entry {
  const found = entries.find((entry) =>
    Object.entries(match).every(([key, value]) => entry[key] === value),
  );
  if (!found) throw new Error(`no entry matching ${JSON.stringify(match)}`);
  return found;
}

const names = (entry: Entry): unknown[] => (entry.entries as Entry[]).map((child) => child.name);

describe("resolveCopies", () => {
  it("leaves a file with no _copy alone", () => {
    const source = { spell: [{ name: "Fireball", source: "PHB" }] };
    const resolved = resolveOne(source, "data/spells/spells-phb.json");
    expect(resolved).toEqual(source);
    expect(resolved.spell).toEqual(source.spell);
  });

  describe("backgrounds.json", () => {
    const backgrounds = load("backgrounds.json", "background");

    it("inherits the parent's own fields and strips the _copy block", () => {
      const acolyte = find(backgrounds, { name: "Baldur's Gate Acolyte" });
      expect(acolyte._copy).toBeUndefined();
      expect(acolyte.skillProficiencies).toEqual([{ insight: true, religion: true }]);
    });

    it("applies insertArr at the index it names", () => {
      const acolyte = find(backgrounds, { name: "Baldur's Gate Acolyte" });
      expect(names(acolyte)).toEqual([
        undefined,
        "Feature: Shelter of the Faithful",
        "Baldur's Gate Feature: Religious Community",
        "Suggested Characteristics",
      ]);
    });

    it("applies replaceArr by the name of the element it replaces", () => {
      expect(names(find(backgrounds, { name: "Variant Criminal (Spy)" }))).toEqual([
        undefined,
        "Feature: Spy Contact",
        "Specialty",
        "Suggested Characteristics",
      ]);
    });

    it("resolves a chain whose parent is itself a copy", () => {
      const augen = find(backgrounds, { name: "Augen Trust (Spy)" });
      expect(names(augen)).toEqual([
        undefined,
        "Feature: Spy Contact",
        "Specialty",
        "Suggested Characteristics",
      ]);
      expect(augen.skillProficiencies).toEqual([{ deception: true, stealth: true }]);
    });

    it("does not inherit metadata the copy did not preserve", () => {
      const augen = find(backgrounds, { name: "Augen Trust (Spy)" });
      expect(augen.page).toBe(203);
      expect(augen.basicRules).toBeUndefined();
    });
  });

  describe("items.json", () => {
    const items = load("items.json", "item");

    it("resolves a four-deep chain, each level keeping its own fields", () => {
      const ascendant = find(items, { name: "Ascendant Dragon Vessel" });
      expect(ascendant.rarity).toBe("legendary");
      expect(ascendant.wondrous).toBe(true);
      expect(ascendant.reqAttune).toBe(true);
      const entries = ascendant.entries as string[];
      expect(entries).toHaveLength(2);
      expect(entries[1]).toContain("{@item potion of supreme healing}");
    });

    it("keeps the parent's page where _preserve names it", () => {
      expect(find(items, { name: "Ascendant Dragon Vessel" }).page).toBe(27);
    });

    it("treats a bare items value as a single-element list", () => {
      const charred = find(items, { name: "Charred Wand of Magic Missiles" });
      expect(charred.entries).toHaveLength(3);
      expect(charred.charges).toBe(7);
      expect(charred.srd).toBeUndefined();
    });
  });

  describe("races.json", () => {
    const races = load("races.json", "race");
    const subraces = load("races.json", "subrace");

    it("matches the parent on source, not name alone", () => {
      const dankwood = find(races, { name: "Goblin (Dankwood)" });
      expect(dankwood.reprintedAs).toEqual(["Goblin|MPMM"]);
    });

    it("applies a list of _mod operations in order", () => {
      const dankwood = find(races, { name: "Goblin (Dankwood)" });
      expect(names(dankwood)).toEqual([
        "Darkvision",
        "Speak with Small Beasts",
        undefined,
        "Alignment",
      ]);
    });

    it("applies replaceTxt to the prose, honoring its flags", () => {
      const [darkvision] = find(races, { name: "Goblin (Dankwood)" }).entries as Entry[];
      expect(darkvision?.entries).toEqual(["Dankwood goblins see in the dark."]);
    });

    it("reaches every prose key of a table, and no structural one", () => {
      const entries = find(races, { name: "Goblin (Dankwood)" }).entries as Entry[];
      const table = entries.find((entry) => entry.type === "table");
      expect(table).toMatchObject({
        type: "table",
        caption: "Dankwood goblins by Type",
        colLabels: ["Dankwood goblins", "Trait"],
        colStyles: ["col-6", "col-6"],
        rows: [["Dankwood goblins", "Nimble Escape"]],
      });
    });

    it("leaves a reference string alone, so replaceTxt cannot break a link", () => {
      const [darkvision] = find(races, { name: "Goblin (Dankwood)" }).entries as Entry[];
      expect(darkvision?.data).toEqual({ overwrite: "Goblins" });
    });

    it("drops a field the child nulls out", () => {
      const boggart = find(races, { name: "Boggart" });
      expect(boggart.speed).toBe(30);
      expect("lineage" in boggart).toBe(false);
    });

    it("keys a subrace by its race as well as its own name and source", () => {
      const amonkhet = find(subraces, { name: "Amonkhet" });
      expect(amonkhet.raceName).toBe("Human");
      expect(amonkhet.raceSource).toBe("PHB");
      expect(names(amonkhet)).toEqual(["Skills", "Age", "Alignment"]);
    });
  });

  describe("class/class-cleric.json", () => {
    const subclasses = load("class/class-cleric.json", "subclass");
    const features = load("class/class-cleric.json", "subclassFeature");

    it("resolves a subclass across editions of the same class", () => {
      const subclass = find(subclasses, { classSource: "XPHB" });
      expect(subclass.page).toBe(59);
      expect(subclass.subclassFeatures).toEqual([
        "Knowledge Domain|Cleric|XPHB|Knowledge||3",
        "Visions of the Past|Cleric||Knowledge||17",
      ]);
    });

    it("does not carry isReprinted onto the row that supersedes it", () => {
      const subclass = find(subclasses, { classSource: "XPHB" });
      expect(subclass.isReprinted).toBeUndefined();
      expect(find(subclasses, { classSource: "PHB" }).isReprinted).toBe(true);
    });

    it("uses every field the _copy block names, so a shared (name, source) is not ambiguous", () => {
      const feature = find(features, { classSource: "XPHB" });
      expect(feature.level).toBe(3);
      expect(feature.header).toBe(2);
      expect(feature.entries).toEqual(["Elided.", "Elided."]);
    });
  });

  describe("failing the build", () => {
    const file = (...entries: Entry[]) => ({
      _meta: { internalCopies: ["background"] },
      background: entries,
    });

    it("names both entries when the parent does not exist", () => {
      expect(() =>
        resolveOne(
          file({ name: "Augen Trust", source: "EGW", _copy: { name: "Spy", source: "PHB" } }),
          "data/backgrounds.json",
        ),
      ).toThrow(
        'data/backgrounds.json background: "Augen Trust" (EGW) copies "Spy" (PHB), which no source the loader declared holds',
      );
    });

    it("names both entries in a cycle", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "A", source: "PHB", _copy: { name: "B", source: "PHB" } },
            { name: "B", source: "PHB", _copy: { name: "A", source: "PHB" } },
          ),
          "data/backgrounds.json",
        ),
      ).toThrow(/"B" \(PHB\) copies "A" \(PHB\), which is already being resolved — _copy cycle/);
    });

    it("catches an entry that copies itself", () => {
      expect(() =>
        resolveOne(
          file({ name: "A", source: "PHB", _copy: { name: "A", source: "PHB" } }),
          "data/backgrounds.json",
        ),
      ).toThrow(/_copy cycle/);
    });

    it("refuses an unsupported _mod mode rather than importing a half-applied record", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "A", source: "PHB", entries: [] },
            {
              name: "B",
              source: "PHB",
              _copy: { name: "A", source: "PHB", _mod: { entries: { mode: "scalarAddHit" } } },
            },
          ),
          "data/backgrounds.json",
        ),
      ).toThrow('unsupported _mod mode "scalarAddHit"');
    });

    it("refuses an array mode with no items rather than splicing in undefined", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "A", source: "PHB", entries: [] },
            {
              name: "B",
              source: "PHB",
              _copy: { name: "A", source: "PHB", _mod: { entries: { mode: "appendArr" } } },
            },
          ),
          "data/backgrounds.json",
        ),
      ).toThrow("appendArr needs items");
    });

    it("appends to a property the parent does not have, rather than refusing", () => {
      const resolved = resolveOne(
        file(
          { name: "A", source: "PHB" },
          {
            name: "B",
            source: "PHB",
            _copy: {
              name: "A",
              source: "PHB",
              _mod: { entries: { mode: "appendArr", items: "Added." } },
            },
          },
        ),
        "data/items.json",
      );

      expect(find(entriesOf(resolved, "background", "items.json"), { name: "B" }).entries).toEqual([
        "Added.",
      ]);
    });

    it("refuses a _mod against a property that is present and not a list", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "A", source: "PHB", entries: "not a list" },
            {
              name: "B",
              source: "PHB",
              _copy: {
                name: "A",
                source: "PHB",
                _mod: { entries: { mode: "appendArr", items: "Added." } },
              },
            },
          ),
          "data/backgrounds.json",
        ),
      ).toThrow("_mod.entries expects a list, found string");
    });

    it("refuses a replaceArr index past the end rather than letting splice clamp", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "A", source: "PHB", entries: [{ name: "Only" }] },
            {
              name: "B",
              source: "PHB",
              _copy: {
                name: "A",
                source: "PHB",
                _mod: { entries: { mode: "replaceArr", replace: { index: 7 }, items: {} } },
              },
            },
          ),
          "data/items.json",
        ),
      ).toThrow("replaceArr index 7 is outside a list of 1");
    });

    it("refuses a replaceTxt with no property to rewrite", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "A", source: "PHB" },
            {
              name: "B",
              source: "PHB",
              _copy: {
                name: "A",
                source: "PHB",
                _mod: { entries: { mode: "replaceTxt", replace: "x", with: "y" } },
              },
            },
          ),
          "data/races.json",
        ),
      ).toThrow("replaceTxt has no entries to rewrite");
    });

    it("refuses a _copy that names no parent instead of cloning the first entry", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "A", source: "PHB", entries: ["Not yours."] },
            { name: "B", source: "PHB", _copy: { _mod: {} } },
          ),
          "data/backgrounds.json",
        ),
      ).toThrow('"B" (PHB) has a _copy that names no parent');
    });

    it("refuses a _copy two entries match instead of cloning whichever comes first", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "Oghma", source: "PHB", pantheon: "Celtic", entries: ["Theirs."] },
            { name: "Oghma", source: "PHB", pantheon: "Forgotten Realms", entries: ["Not yours."] },
            { name: "Oghma", source: "VGM", _copy: { name: "Oghma", source: "PHB" } },
          ),
          "data/backgrounds.json",
        ),
      ).toThrow('copies "Oghma" (PHB), which 2 entries match');
    });

    it("takes the one parent a block names once a key tells the twins apart", () => {
      const resolved = resolveOne(
        file(
          { name: "Oghma", source: "PHB", pantheon: "Celtic", entries: ["Theirs."] },
          { name: "Oghma", source: "PHB", pantheon: "Forgotten Realms", entries: ["Yours."] },
          {
            name: "Oghma",
            source: "VGM",
            _copy: { name: "Oghma", source: "PHB", pantheon: "Forgotten Realms" },
          },
        ),
        "data/backgrounds.json",
      ) as { background: Entry[] };

      expect(resolved.background[2]?.entries).toEqual(["Yours."]);
    });

    const copying = (mod: unknown) => ({
      name: "B",
      source: "PHB",
      _copy: { name: "A", source: "PHB", _mod: mod },
    });

    it("removes the named elements, and is available to a _copy as to a version", () => {
      const resolved = resolveOne(
        file(
          { name: "A", source: "PHB", entries: [{ name: "One" }, { name: "Two" }, { name: "3" }] },
          copying({ entries: { mode: "removeArr", names: ["One", "3"] } }),
        ),
        "data/backgrounds.json",
      ) as { background: Entry[] };

      expect(names(resolved.background[1] as Entry)).toEqual(["Two"]);
    });

    it("refuses a removeArr naming an element the list does not hold", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "A", source: "PHB", entries: [{ name: "One" }] },
            copying({ entries: { mode: "removeArr", names: ["One", "Missing"] } }),
          ),
          "data/backgrounds.json",
        ),
      ).toThrow('removeArr names "Missing", which entries does not hold');
    });

    it("checks each name, so a repeated one cannot cover for a typo", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "A", source: "PHB", entries: [{ name: "One" }, { name: "One" }] },
            copying({ entries: { mode: "removeArr", names: ["One", "Typo"] } }),
          ),
          "data/backgrounds.json",
        ),
      ).toThrow('removeArr names "Typo", which entries does not hold');
    });

    it("refuses a removeArr with nothing to remove at all, not only an empty list", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "A", source: "PHB", entries: [{ name: "One" }] },
            copying({ entries: { mode: "removeArr" } }),
          ),
          "data/backgrounds.json",
        ),
      ).toThrow("removeArr needs names or items");
    });

    it("treats a removeArr against a property the entry lacks as nothing to remove", () => {
      const resolved = resolveOne(
        file(
          { name: "A", source: "PHB" },
          copying({ entries: { mode: "removeArr", names: "Anything" } }),
        ),
        "data/backgrounds.json",
      ) as { background: Entry[] };

      expect(resolved.background[1]).not.toHaveProperty("entries");
    });

    /**
     * Every array property is resolved now, entity or not, so the scan meets
     * arrays of strings and nulls that no loader would have handed it. One is
     * passed through rather than reported: it carries no `_copy` to resolve and
     * matches no `_copy` block, and refusing would fail a build over an array
     * that has nothing to do with inheritance.
     */
    it("passes a non-object element through instead of reading it as an entry", () => {
      const resolved = resolveOne(
        {
          background: [{ name: "A", source: "PHB" }, null, "text"],
          colLabels: ["Name", "Source"],
        },
        "data/x.json",
      );

      expect(resolved.background).toEqual([{ name: "A", source: "PHB" }, null, "text"]);
      expect(resolved.colLabels).toEqual(["Name", "Source"]);
    });

    it("refuses an insertArr index past the end, the way replaceArr does", () => {
      const at = (index: number) =>
        resolveOne(
          file(
            { name: "A", source: "PHB", entries: ["One", "Two"] },
            {
              name: "B",
              source: "PHB",
              _copy: {
                name: "A",
                source: "PHB",
                _mod: { entries: { mode: "insertArr", index, items: "New." } },
              },
            },
          ),
          "data/items.json",
        ) as { background: Entry[] };

      // `length` is an append, and -length is the front — both legitimate.
      expect(find(at(2).background, { name: "B" }).entries).toEqual(["One", "Two", "New."]);
      expect(find(at(-2).background, { name: "B" }).entries).toEqual(["New.", "One", "Two"]);
      expect(() => at(3)).toThrow("insertArr index 3 is outside a list of 2");
      expect(() => at(-3)).toThrow("insertArr index -3 is outside a list of 2");
    });

    it("rewrites a scalar property with replaceTxt rather than demanding a list", () => {
      const resolved = resolveOne(
        file(
          { name: "A", source: "PHB", fluff: "Goblins everywhere." },
          {
            name: "B",
            source: "PHB",
            _copy: {
              name: "A",
              source: "PHB",
              _mod: { fluff: { mode: "replaceTxt", replace: "Goblins", with: "Kobolds" } },
            },
          },
        ),
        "data/races.json",
      );

      expect(find(entriesOf(resolved, "background", "races.json"), { name: "B" }).fluff).toBe(
        "Kobolds everywhere.",
      );
    });

    it.each(["_copy", "_mod", "_preserve"])("refuses a malformed %s", (key) => {
      const copy: Entry = { name: "A", source: "PHB" };
      const child: Entry = { name: "B", source: "PHB", _copy: copy };
      if (key === "_copy") child._copy = "A|PHB";
      else copy[key] = [{ mode: "appendArr", items: "x" }];

      expect(() =>
        resolveOne(file({ name: "A", source: "PHB" }, child), "data/backgrounds.json"),
      ).toThrow(`"B" (PHB) has a ${key} that is not an object`);
    });

    it("reports a replaceArr whose target is not there", () => {
      expect(() =>
        resolveOne(
          file(
            { name: "A", source: "PHB", entries: [{ name: "Kept" }] },
            {
              name: "B",
              source: "PHB",
              _copy: {
                name: "A",
                source: "PHB",
                _mod: { entries: { mode: "replaceArr", replace: "Gone", items: {} } },
              },
            },
          ),
          "data/backgrounds.json",
        ),
      ).toThrow('replaceArr matched no element named "Gone"');
    });
  });

  /**
   * The shapes only `data/bestiary/` writes. Character data reaches none of them,
   * which is why they went unhandled until a loader read everything.
   */
  describe("across the declared sources", () => {
    const monsters = (...entries: Entry[]) => ({ monster: entries });

    it("finds a parent in another source", () => {
      const resolved = resolveCopies(
        new Map<string, unknown>([
          ["data/bestiary/bestiary-mm.json", monsters({ name: "Zombie", source: "MM", cr: "1/4" })],
          [
            "data/bestiary/bestiary-pabtso.json",
            monsters({
              name: "Ash Zombie",
              source: "PaBTSO",
              _copy: { name: "Zombie", source: "MM" },
            }),
          ],
        ]),
      );

      const child = entriesOf(
        resolved.get("data/bestiary/bestiary-pabtso.json") as Entry,
        "monster",
        "bestiary-pabtso.json",
      );
      expect(child[0]).toEqual({ name: "Ash Zombie", source: "PaBTSO", cr: "1/4" });
    });

    /**
     * `Ougalop` (OotA) is the entry that needs this: it copies `Kuo-Toa` (MM),
     * and upstream spells that monster `Kuo-toa`. Their own lookup lowercases a
     * key before matching, so the typo has never shown up for them.
     */
    it("matches a parent whose name differs only in case", () => {
      const resolved = resolveOne(
        monsters(
          { name: "Kuo-toa", source: "MM", cr: "1/4" },
          { name: "Ougalop", source: "OotA", _copy: { name: "Kuo-Toa", source: "MM" } },
        ),
        "data/bestiary/bestiary-oota.json",
      );

      expect(entriesOf(resolved, "monster", "oota")[1]).toEqual({
        name: "Ougalop",
        source: "OotA",
        cr: "1/4",
      });
    });

    it("resolves a property that _meta.internalCopies does not name", () => {
      const resolved = resolveOne(
        {
          _meta: { internalCopies: ["background"] },
          background: [{ name: "Acolyte", source: "PHB" }],
          itemGroup: [
            { name: "Robes", source: "PHB", entries: ["Cloth."] },
            { name: "Vestments", source: "PHB", _copy: { name: "Robes", source: "PHB" } },
          ],
        },
        "data/items.json",
      );

      expect(entriesOf(resolved, "itemGroup", "items.json")[1]).toEqual({
        name: "Vestments",
        source: "PHB",
        entries: ["Cloth."],
      });
    });

    it("still refuses a parent two sources both hold", () => {
      expect(() =>
        resolveCopies(
          new Map<string, unknown>([
            [
              "data/class/class-fighter.json",
              { subclass: [{ name: "Battle Master", source: "PHB" }] },
            ],
            ["data/class/foundry.json", { subclass: [{ name: "Battle Master", source: "PHB" }] }],
            [
              "data/class/class-ranger.json",
              {
                subclass: [
                  {
                    name: "Gloom Stalker",
                    source: "XGE",
                    _copy: { name: "Battle Master", source: "PHB" },
                  },
                ],
              },
            ],
          ]),
        ),
      ).toThrow('copies "Battle Master" (PHB), which 2 entries match');
    });

    it("names both entries in a cycle that spans two sources", () => {
      expect(() =>
        resolveCopies(
          new Map<string, unknown>([
            [
              "data/bestiary/a.json",
              monsters({ name: "A", source: "MM", _copy: { name: "B", source: "MM" } }),
            ],
            [
              "data/bestiary/b.json",
              monsters({ name: "B", source: "MM", _copy: { name: "A", source: "MM" } }),
            ],
          ]),
        ),
      ).toThrow(/_copy cycle/);
    });
  });

  describe("a _mod that does not name one property", () => {
    const copying = (mod: unknown, parent: Entry) => ({
      monster: [
        parent,
        { name: "Child", source: "BGDIA", _copy: { name: "Parent", source: "MM", _mod: mod } },
      ],
    });

    const child = (mod: unknown, parent: Entry): Entry =>
      entriesOf(
        resolveOne(copying(mod, parent), "data/bestiary/x.json"),
        "monster",
        "x",
      )[1] as Entry;

    /**
     * `Bitter Breath` (BGDIA) is a Horned Devil renamed throughout its stat block.
     * Upstream writes one rewrite against `*` rather than naming each section that
     * says "the devil", so every section holding rules text has to see it.
     */
    it("applies a * operation to every prose section", () => {
      const renamed = child(
        { "*": { mode: "replaceTxt", replace: "the devil", with: "Bitter Breath", flags: "i" } },
        {
          name: "Parent",
          source: "MM",
          trait: [{ name: "Devil's Sight", entries: ["Darkness does not impede the devil."] }],
          action: [{ name: "Multiattack", entries: ["The devil makes three attacks."] }],
          reaction: [{ name: "Parry", entries: ["The devil adds 4 to its AC."] }],
        },
      );

      expect(renamed.trait).toEqual([
        { name: "Devil's Sight", entries: ["Darkness does not impede Bitter Breath."] },
      ]);
      expect(renamed.action).toEqual([
        { name: "Multiattack", entries: ["Bitter Breath makes three attacks."] },
      ]);
      expect(renamed.reaction).toEqual([
        { name: "Parry", entries: ["Bitter Breath adds 4 to its AC."] },
      ]);
    });

    /**
     * A rename let loose on the whole entry rewrites what is not prose, and the
     * bestiary shows every way that goes wrong at once. `Ctenmiir the Vampire`
     * (LLK) is the identity case — its `*` replaces "the vampire" with
     * "Ctenmiir", and its own name already ends in the words being replaced.
     */
    it("leaves identity, references and machine fields out of a * operation", () => {
      const renamed = child(
        { "*": { mode: "replaceTxt", replace: "the vampire", with: "Ctenmiir", flags: "i" } },
        {
          name: "Parent",
          source: "MM",
          type: "undead",
          soundClip: { type: "internal", path: "bestiary/the-vampire.opus" },
          legendaryGroup: { name: "The Vampire", source: "MM" },
          ac: [{ ac: 15, condition: "with {@spell the vampire armor}" }],
          languages: ["The Vampire"],
          trait: [{ name: "Regeneration", entries: ["The vampire regains 20 hit points."] }],
        },
      );

      expect(renamed.name).toBe("Child");
      expect(renamed.type).toBe("undead");
      expect(renamed.soundClip).toEqual({ type: "internal", path: "bestiary/the-vampire.opus" });
      expect(renamed.legendaryGroup).toEqual({ name: "The Vampire", source: "MM" });
      expect(renamed.ac).toEqual([{ ac: 15, condition: "with {@spell the vampire armor}" }]);
      expect(renamed.languages).toEqual(["The Vampire"]);
      expect(renamed.trait).toEqual([
        { name: "Regeneration", entries: ["Ctenmiir regains 20 hit points."] },
      ]);
    });

    it("writes a _ setProp at the dotted path it names", () => {
      const written = child(
        { _: { mode: "setProp", prop: "apply._root.type", value: { type: "humanoid" } } },
        { name: "Parent", source: "MM", apply: { _root: { type: "beast", size: ["M"] } } },
      );

      expect(written.apply).toEqual({ _root: { type: { type: "humanoid" }, size: ["M"] } });
    });

    it("refuses a _ setProp that names no prop", () => {
      expect(() =>
        child({ _: { mode: "setProp", value: 1 } }, { name: "Parent", source: "MM" }),
      ).toThrow("a whole-entry setProp has to name its prop");
    });

    it("refuses a whole-entry mode it does not implement", () => {
      expect(() =>
        child({ _: { mode: "addSenses", senses: {} } }, { name: "Parent", source: "MM" }),
      ).toThrow('unsupported whole-entry _mod mode "addSenses"');
    });

    /** `Cat Skeleton` (CoS) erases the vulnerability its parent has this way. */
    it("erases a property through a _ setProp of null", () => {
      const erased = child(
        { _: { mode: "setProp", prop: "vulnerable", value: null } },
        {
          name: "Parent",
          source: "MM",
          vulnerable: ["bludgeoning"],
        },
      );

      expect(erased).not.toHaveProperty("vulnerable");
    });

    /** `Arabelle` (CoS) is a Commoner that does nothing on its turn. */
    it("deletes a property written as a bare remove", () => {
      const stripped = child(
        { action: "remove" },
        {
          name: "Parent",
          source: "MM",
          action: [{ name: "Club" }],
        },
      );

      expect(stripped).not.toHaveProperty("action");
    });

    it("refuses a bare word that is not remove", () => {
      expect(() => child({ action: "delete" }, { name: "Parent", source: "MM" })).toThrow(
        '_mod.action is "delete", which is not an operation',
      );
    });

    /** `Blurg` (OotA) is a Deep Gnome who already speaks Undercommon. */
    it("appends only what a list does not already hold", () => {
      const spoken = child(
        {
          languages: {
            mode: "appendIfNotExistsArr",
            items: ["Dwarvish", "Elvish", "Undercommon"],
          },
        },
        { name: "Parent", source: "MM", languages: ["Gnomish", "Undercommon"] },
      );

      expect(spoken.languages).toEqual(["Gnomish", "Undercommon", "Dwarvish", "Elvish"]);
    });

    /** 35 fluff entries replace their parent's prose with a setProp and no `prop`. */
    it("writes a setProp with no prop at the property it sits under", () => {
      const rewritten = child(
        { entries: { mode: "setProp", value: ["Ours."] } },
        {
          name: "Parent",
          source: "MM",
          entries: ["Theirs."],
        },
      );

      expect(rewritten.entries).toEqual(["Ours."]);
    });
  });
});
